# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy to gh-pages

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependency
        run: yarn install -D
  
      - name: Build
        run: yarn run build    

      - name: Checkout legacy version
        uses: actions/checkout@v4
        with:
          ref: legacy
          clean: false

      - name: Install dependency
        run: yarn install -D
  
      - name: Build legacy version
        run: yarn run build    

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
          enable_jekyll: true
          force_orphan: true
